### ISSUE TITLE
Crash at train purchase window

### ISSUE THREAD

**Issue by KeepinItRail** [JGRennison/OpenTTD-patches#297]
Hey

Love the new changes in v0.42.0. Great work!

I am experiencing a crash though with one of the new updates. I've attached the crash logs. I also could replicate the crash when I removed all newGRFs,

### Steps to Replicate

I got a crash when I filtered wagons (for Oil) and click the TAMU Tanker (JapanSet) in the purchase trains window.

[crash-20210705T061325Z.log](https://github.com/JGRennison/OpenTTD-patches/files/6763620/crash-20210705T061325Z.log)
![crash-20210705T061325Z](https://user-images.githubusercontent.com/74462886/124459539-23bee000-dd86-11eb-8528-3c725b453f69.png)
[crash-20210705T061325Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/6763623/crash-20210705T061325Z.zip)

I then removed all newGRFs and still get the crash.

[crash-20210705T140010Z.log](https://github.com/JGRennison/OpenTTD-patches/files/6764775/crash-20210705T140010Z.log)
![crash-20210705T140010Z](https://user-images.githubusercontent.com/74462886/124483390-321af500-dda2-11eb-93ec-1e0775451ead.png)
[crash-20210705T140010Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/6764790/crash-20210705T140010Z.zip)

I also notice, in game the 'Buy wagon' button is greyed out, however in the crash screenshots, it is looking normal. Below is an example of what it looks like before the crash.
![image](https://user-images.githubusercontent.com/74462886/124483889-bbcac280-dda2-11eb-9fa3-c2ecc2383bdf.png)

**Comment by James103** [comment]
I get the same crash as well with similar reproduction steps:
[crash_train_purchase_window.zip](https://github.com/JGRennison/OpenTTD-patches/files/6764976/crash_train_purchase_window.zip)

**Comment by JGRennison** [comment]
Should be fixed by 5230ff5e8d0e00cb6273ed2766b744322eb6faee

**Comment by Gugui322** [comment]
> 
> 
> I get the same crash as well with similar reproduction steps:
> [crash_train_purchase_window.zip](https://github.com/JGRennison/OpenTTD-patches/files/6764976/crash_train_purchase_window.zip)

[OpenTTD.zip](https://github.com/JGRennison/OpenTTD-patches/files/6780109/OpenTTD.zip)

Same thing here.

**Comment by James103** [comment]
For those that experience the same crash and/or incorrect info, do the following:
1. Turn off the setting: "Separate locomotives and wagons in the train purchase window".
2. Do not turn that setting back on until AFTER you have done the following:
   * Wait until jgrpp-0.42.1 or jgrpp-0.43.0 is released.
   * Update to that newer version.
5. Only then should you turn that setting back on.

**Comment by auge8472** [comment]
I got a similar crash with JGRPP 0.42.1.
[crash-auge-20210709T122636Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/6790738/crash-auge-20210709T122636Z.zip)

**Comment by James103** [comment]
With OpenTTD jgrpp-0.42.1, I'm still getting various incorrect information with the separated train purchase window. For example, the cargo filter needs to be changed in order for the displayed capacity to update. I have not been able to reproduce a crash yet.

**Comment by auge8472** [comment]
I also encountered wrong capacities in the train purchase window with 0.42.1. The locomotive I bought (from the SBB set), is a railcar with a capacity of 24 mail bags. In the new purchase window it was announced with a capacity of only 12 mail bags. After buying it, the vehicle window stated it with the correct capacity of 24 mail bag

In the old purchase window the railcar gets announced with the correct capacity of 24 mail bags. So this also seems to be an issue with the new purchase window.

**Comment by JGRennison** [comment]
This should be fixed in 0.42.3
